name: JDI Dark Examples

on:
  push:
    branches:
      - master
      - add_ci
  pull_request:
    branches:
      - master
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    name: Run tests for JDK
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14] # all [8, 9, 10, 11, 12, 13, 14], only one is [8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
      - name: Prepare environment
        run: |
          sudo chmod +x ./gradlew
          sudo apt-get -y install jq
          java -Xmx32m -version
          env

      - name: Welcome to JDI
        run: |
          echo ------------------- WELCOME TO JDI DARK EXAMPLE ------------------
          mvn --version

      - name: Compile jdi-example code Maven
        id: jdi-mvn-compile
        run: mvn clean install -DskipTests

      - name: Run tests - Maven
        id: mvn-tests
        timeout-minutes: 10 # prevent blocking
        run: mvn verify --fail-at-end

      - name: Compile and test jdi-example code Gradle
        id: jdi-gradle-compile
        timeout-minutes: 10 # prevent blocking
        run: ./gradlew build --rerun-tasks